version: "3.8"
name: "vstats"
services:
  database:
    container_name: postgres
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - vstats-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vstats
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password


volumes:
  vstats-postgres:
